### ISSUE TITLE
Element extraction in original order

### ISSUE THREAD

**Issue by zheyaf** [jstockwin/py-pdf-parser#190]
Hi,

There are four ordering options in the current parser. They are all position orderings which reflect the visual structure of a pdf. Is it possible to support the original ordering parsing, so parsing it following the order as in the pdf source code? 
This would allow us to understand the pdf generation, for example, in the case where a text box and a rectangle in the same position, we can know from the object order in source code that which one was add before the other one.

Thanks!

**Comment by jstockwin** [comment]
Hello,

Thanks for the question!

As well as those four ordering options, you can pass a custom ordering into the loaders using the `element_ordering` argument. You can see the documentation for this in the arguments of `PDFDocument` [here](https://py-pdf-parser.readthedocs.io/en/latest/reference/components.html#py_pdf_parser.components.PDFDocument), and you can see some example usage [here](https://py-pdf-parser.readthedocs.io/en/latest/examples/element_ordering.html#custom-ordering).

Passing a function that does nothing will mean we (`py-pdf-paser`) don't change the ordering, i.e. you can try:
```
load_file(file_path, element_ordering=lambda elements: elements)
```

That said, the `elements` which this element ordering function get are the result of calling to [pdfminer.six](https://github.com/pdfminer/pdfminer.six) (which is what `py-pdf-parser` uses to do the actual pdf extraction), and pdfminer.six does a lot of layout analysis (using the `la_params` that you pass). Pdfminer.six is what is grouping things into text boxes etc, and I'm pretty sure this will have already changed the order.

Note that even if you do manage to get the original order, a lot of the functionality in `py-pdf-parser` is designed to filter based on the position on the page (i.e. the visual structure). If you're trying to work on just the element order there will be some restrictions on which functions will be suitable.

I think the most likely short answer is that pdfminer.six do not support this, and therefore nor does `py-pdf-parser`. Since most of this project will be about the visual structure, it is likely that this project isn't the best suited to what you need.

I hope that helps, although I appreciate it might not be the answer you were hoping for.

Do let me know if there's anything else I can help with, and otherwise if we can close the issue.

**Comment by zheyaf** [comment]
Thanks for reply and information!
I'll look for other solutions, and great project!
