### ISSUE TITLE
`create_section` should throw a better error if it isn't passed a `PDFElement`

### ISSUE THREAD

**Issue by jstockwin** [jstockwin/py-pdf-parser#75]
It's easy to accidentally pass an `ElementList` as the start/end element, for example, and then the error thrown is `AttributeError: 'ElementList' object has no attribute '_index'`. This is not very clear and should be improved.

**Comment by paulopaixaoamaral** [comment]
@jstockwin There is a circular import problem here: in order to verify if `start_element` and `end_element` are instances of `PDFElement` we need to import `PDFElement` from `components` in `sectioning.py`, but the sectioning module is already being imported in `components.py`.

Any better ideas than to import `PDFElement` in the `create_section` function itself?

**Comment by jstockwin** [comment]
Hum, yeah that's annoying...

My only other suggestions are:

- add some kind of `_validate_pdf_element(element)` function to the `PDFDocument`, and then `create_section` can do `self.document._validate_pdf_element`. Seems grim though.

- do it a duck-typing way and just check that whatever was passed has `_index`, but that seems grim? We could literally just catch the `AttributeError`.

- really, it doesn't make sense to pass ANY PDFElement, it must be one from the document. So maybe we should be checking `start_element in self.document.elements`. I think this just shifts the problem over to `filtering.py`, though?

We don't do this validation anywhere, I guess. I.e. none of the other filtering functions check that the arguments were passed correctly, and I don't really want to go and add it everywhere.

Perhaps we should just decide that type checking would pick this up, and so it's not an issue...

Thoughts, @paulopaixaoamaral?

**Comment by paulopaixaoamaral** [comment]
I think that although your last suggestion seems the more plausible one, I agree that since we are not validating input anywhere else than doing it here seems weird.

I feel that, although the error message is a bit confusing, it is not that complex to debug and since Python developers are used to not having type validation on inputs it would be cumbersome to add this validation everywhere.

Should we close this issue as a `wontfix`?

**Comment by jstockwin** [comment]
Cool, I agree I think we shouldn't go down the road of adding type validation everywhere. We have type hints, people can follow them. Closing.
